my_gen3:
    # Settings for ros_control hardware interface
  hardware_interface:
    joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6
        - joint_7
        - gripper_finger1_joint
    sim_control_mode: 0  # 0: position, 1: velocity
    
  ## Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
    controller_list:
    - name: arm_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6
        - joint_7
  gen3_joint_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6
        - joint_7
    constraints:
        goal_time: 1.0
        stopped_velocity_tolerance: 0.5
    stop_trajectory_duration: 1.0
    state_publish_rate:  25
    action_monitor_rate: 25
    gains:
        joint_1: {p: 30000.0, i: 0.0, d: 2.0, i_clamp_min: -100.0, i_clamp_max: 100.0}
        joint_2: {p: 50000.0, i: 0.0, d: 0.0, i_clamp_min: -5.0, i_clamp_max: 5.0}
        joint_3: {p: 3000.0, i: 0.0, d: 0.0, i_clamp_min: -1.0, i_clamp_max: 1.0}
        joint_4: {p: 50000.0, i: 0.0, d: 0.0, i_clamp_min: -1.0, i_clamp_max: 1.0}
        joint_5: {p: 750.0, i: 0.0, d: 0.2, i_clamp_min: -1.0, i_clamp_max: 1.0}
        joint_6: {p: 5000.0, i: 0.0, d: 1.0, i_clamp_min: -1.0, i_clamp_max: 1.0}
        joint_7: {p: 100.0, i: 0.0, d: 0.0, i_clamp_min: -0.1, i_clamp_max: 0.1}
        
        
  robotiq_2f_85_gripper_controller:
    type: position_controllers/GripperActionController
    joint: finger_joint
    action_monitor_rate: 100


  gazebo_ros_control/pid_gains:
        joint_1: {p: 30000.0, i: 0.0, d: 2.0, i_clamp_min: -100.0, i_clamp_max: 100.0}
        joint_2: {p: 50000.0, i: 0.0, d: 0.0, i_clamp_min: -5.0, i_clamp_max: 5.0}
        joint_3: {p: 3000.0, i: 0.0, d: 0.0, i_clamp_min: -1.0, i_clamp_max: 1.0}
        joint_4: {p: 50000.0, i: 0.0, d: 0.0, i_clamp_min: -1.0, i_clamp_max: 1.0}
        joint_5: {p: 750.0, i: 0.0, d: 0.2, i_clamp_min: -1.0, i_clamp_max: 1.0}
        joint_6: {p: 5000.0, i: 0.0, d: 1.0, i_clamp_min: -1.0, i_clamp_max: 1.0}
        joint_7: {p: 100.0, i: 0.0, d: 0.0, i_clamp_min: -0.1, i_clamp_max: 0.1}

        
  #
  # Position Controllers ---------------------------------------
  #
  

  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_1
    pid: {p: 30000.0, i: 0.0, d: 2.0}
  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_2
    pid: {p: 50000.0, i: 0.0, d: 0.0}
  joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_3
    pid: {p: 30000.0, i: 0.0, d: 0.0}
  joint4_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_4
    pid: {p: 50000.0, i: 0.0, d: 0.0}
  joint5_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_5
    pid: {p: 7500.0, i: 0.0, d: 0.2}
  joint6_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_6
    pid: {p: 5000.0, i: 0.0, d: 1.0}
  joint7_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_7
    pid: {p: 1000.0, i: 0.0, d: 0.0}
  gripper_finger1_joint_controller:
    type: effort_controllers/JointPositionController
    joint: finger1_joint
    pid: {p: 10.0, i: 0.0, d: 0.01}
  gripper_finger1_inner_knuckle_joint_controller:
    type: effort_controllers/JointPositionController
    joint: finger1_inner_knuckle_joint
    pid: {p: 10.0, i: 0.0, d: 0.01} 
  gripper_finger1_finger_tip_joint_controller:
    type: effort_controllers/JointPositionController
    joint: finger1_finger_tip_joint
    pid: {p: 10.0, i: 0.0, d: 0.00} 
  gripper_finger2_joint_controller:
    type: effort_controllers/JointPositionController
    joint: finger2_joint
    pid: {p: 10.0, i: 0.0, d: 0.01}
  gripper_finger2_inner_knuckle_joint_controller:
    type: effort_controllers/JointPositionController
    joint: finger2_inner_knuckle_joint
    pid: {p: 10.0, i: 0.0, d: 0.01} 
  gripper_finger2_finger_tip_joint_controller:
    type: effort_controllers/JointPositionController
    joint: finger2_finger_tip_joint
    pid: {p: 10.0, i: 0.0, d: 0.00}

 
    
